### ISSUE TITLE
props.style key `color` error

### ISSUE THREAD

**Issue by dnizfor** [sevvaleygul0/react-native-language-picker#2]
Hello, I am using your package . I get this error. The problem in lib/languageItems.style.tsx. You use color props for Image but Image havent color props. You can use tintColor or backgroundColor.[ Click here for more detail.](https://reactnative.dev/docs/image-style-props)  Other than that, thanks for this excellent repo!

![21](https://github.com/sevvaleygul0/react-native-language-select/assets/86577022/d6a3eb9e-c809-4cf9-8cea-d58706346f92)
![1](https://github.com/sevvaleygul0/react-native-language-select/assets/86577022/23b46944-7031-4311-b298-86a930439da4)

Warning: Failed %s type: %s%s, prop, Invalid props.style key `color` supplied to `Image`.
Bad object: {
  "position": "absolute",
  "right": 24,
  "width": 20,
  "height": 20,
  "color": "red"
}
Valid keys: [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "borderBottomWidth",
  "borderEndWidth",
  "borderLeftWidth",
  "borderRightWidth",
  "borderStartWidth",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "columnGap",
  "direction",
  "display",
  "end",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "gap",
  "height",
  "justifyContent",
  "left",
  "margin",
  "marginBlock",
  "marginBlockEnd",
  "marginBlockStart",
  "marginBottom",
  "marginEnd",
  "marginHorizontal",
  "marginInline",
  "marginInlineEnd",
  "marginInlineStart",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "overflow",
  "padding",
  "paddingBlock",
  "paddingBlockEnd",
  "paddingBlockStart",
  "paddingBottom",
  "paddingEnd",
  "paddingHorizontal",
  "paddingInline",
  "paddingInlineEnd",
  "paddingInlineStart",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingTop",
  "paddingVertical",
  "position",
  "right",
  "rowGap",
  "start",
  "top",
  "width",
  "zIndex",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "objectFit",
  "opacity",
  "overlayColor",
  "tintColor",
  "resizeMode"
], 
    at BaseImage (http://192.168.1.41:19000/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&strict=false&minify=false:58716:70)
    in LanguageItem (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in VirtualizedListCellContextProvider (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by LanguagePicker)
    in LanguagePicker (created by LanguageSelectScreen)
    in RCTView (created by View)
    in View (created by LanguageSelectScreen)
    in LanguageSelectScreen (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules\react\cjs\react-jsx-runtime.development.js:null in printWarning
at node_modules\react\cjs\react-jsx-runtime.development.js:null in error
- ... 27 more stack frames from framework internals

**Comment by wtfkimi** [comment]
same error
